### ISSUE TITLE
The OpenGraph image is missing

### ISSUE THREAD

**Issue by alexisLefebvre** [hamaluik/nomdebebe#7]
See here:

https://github.com/hamaluik/nomdebebe/blob/4c137319bc88dbdaf369a593f4f51723fa84a2a7/website/public/index.html#L14

That image doesn't exist: https://nomdebebe.app/image.jpg

There are some available images in the [images directory](https://github.com/hamaluik/nomdebebe/tree/main/website/public/images) but the PNG is too big and I don't know if webp will be supported by all clients (Slack, Mattermost, WhatsApp, etc.).

**Comment by hamaluik** [comment]
Thanks for spotting that!
